pipeline {
    agent any

    stages {

        stage('Checkout From GitHub') {
            steps {
                checkout scm
            }
        }

        stage('Verify SF CLI') {
            steps {
                bat 'sf --version'
            }
        }

        stage('Verify Org') {
            steps {
                bat 'sf org list'
            }
        }

        stage('Deploy Apex Classes') {
            steps {
                bat '''
                sf project deploy start ^
                --metadata ApexClass:JenkinsDemo ^
                --metadata ApexClass:JenkinsDemoTest ^
                --target-org yogi81102.3781dfe9b859@agentforce.com ^
                --test-level RunSpecifiedTests ^
                --tests JenkinsDemoTest ^
                --wait 60
                '''
            }
        }
    }

    post {

        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}
