pipeline {
    agent any

    stages {
        stage('Checkout From GitHub') {
            steps {
                checkout scm
            }
        }

        stage('Verify SF CLI') {
            steps {
                bat 'sf --version'
            }
        }

        stage('Authenticate Salesforce') {
            steps {
                // 1. Pull the Secret Text securely into this specific stage
                withCredentials([string(credentialsId: 'sf-auth-url', variable: 'SF_AUTH_URL')]) {
                    
                    // 2. Write the secret to a temporary file (silently)
                    writeFile file: 'sfdx_auth.txt', text: SF_AUTH_URL
                    
                    // 3. Authorize the Salesforce CLI using the file and set the alias
                    bat 'sf org login sfdx-url --sfdx-url-file sfdx_auth.txt --alias JenkinsOrg --set-default'
                    
                    // 4. Delete the file immediately to keep the workspace secure
                    bat 'del sfdx_auth.txt'
                }
            }
        }

        stage('Verify Org') {
            steps {
                bat 'sf org list'
            }
        }

        stage('Deploy Apex Classes') {
            steps {
                bat '''
                sf project deploy start ^
                --metadata ApexClass:JenkinsDemo ^
                --metadata ApexClass:JenkinsDemoTest ^
                --target-org yogi81102.3781dfe9b859@agentforce.com ^
                --test-level RunSpecifiedTests ^
                --tests JenkinsDemoTest ^
                --wait 60
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}
